keys:
  - &host_zephyrus age1z2km2vu3mw6usw8p2rhjzkugddmsvk0ypwjw76cscyy3ar3tnufqtrv3nu
  - &host_zen age135k4636aftqw524cuspnwd7hrcneu7q37k3upllaeuk9ud3k738sesr3wh
  - &guest_polder age1ujmcgec6edn3uqzggaec06va2d0us0na5dvlwa30w8gglp4635ysy8022p

creation_rules:
  - path_regex: secrets/.*\.yaml
    key_groups:
      - age:
        - *host_zephyrus
        - *host_zen
        - *guest_polder
