[rime_wanxiang_zrm]
src.github = "amzxyz/rime_wanxiang"
fetch.url = "https://github.com/amzxyz/rime_wanxiang/releases/download/$ver/rime-wanxiang-zrm-fuzhu.zip"

[rime_wanxiang_flypy]
src.github = "amzxyz/rime_wanxiang"
fetch.url = "https://github.com/amzxyz/rime_wanxiang/releases/download/$ver/rime-wanxiang-flypy-fuzhu.zip"

[RIME-LMDG]
src.github = "amzxyz/RIME-LMDG"
fetch.url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram"

[bbdown-linux-x64]
src.github = "nilaoda/BBDown"
fetch.url = "https://github.com/nilaoda/BBDown/releases/download/$ver/BBDown_$ver_20240814_linux-x64.zip"

[bbdown-linux-arm64]
src.github = "nilaoda/BBDown"
fetch.url = "https://github.com/nilaoda/BBDown/releases/download/$ver/BBDown_$ver_20240814_linux-arm64.zip"

[bbdown-osx-arm64]
src.github = "nilaoda/BBDown"
fetch.url = "https://github.com/nilaoda/BBDown/releases/download/$ver/BBDown_$ver_20240814_osx-arm64.zip"

[noname]
src.github = "libnoname/noname"
fetch.github = "libnoname/noname"

[dwproton-linux-x64]
src.cmd = "curl -sSL https://dawn.wine/api/v1/repos/dawn-winery/dwproton/releases/latest | jq -r .tag_name"
fetch.url = "https://dawn.wine/dawn-winery/dwproton/releases/download/$ver/$ver-x86_64.tar.xz"
