# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  RIME-LMDG = {
    pname = "RIME-LMDG";
    version = "tool";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram";
      sha256 = "sha256-Pr3wgPM9TzYY8medb540opC9dZBvQrnXU/Yw5RAeVAc=";
    };
  };
  bbdown-linux-arm64 = {
    pname = "bbdown-linux-arm64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_linux-arm64.zip";
      sha256 = "sha256-9Y4KGN8aWJN1QooK8n6mH1zpb/r2fRFfM11fm+6aNNw=";
    };
  };
  bbdown-linux-x64 = {
    pname = "bbdown-linux-x64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_linux-x64.zip";
      sha256 = "sha256-7CM7fY1AscxER9rAW+ND9Tp1fcYFdDqICKuqjpfl0Q4=";
    };
  };
  bbdown-osx-arm64 = {
    pname = "bbdown-osx-arm64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_osx-arm64.zip";
      sha256 = "sha256-TfhAFNgYvW3/KzZbhHZFNA6JVcRFD+llaI9Br4mji6o=";
    };
  };
  go-fast-note-sync = {
    pname = "go-fast-note-sync";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "erichll";
      repo = "go-fast-note-sync";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-wgtzH5NdkzjXfYUIk9xvugv+QUTWxvlkhor6kkBYZsc=";
    };
  };
  lobe-icons = {
    pname = "lobe-icons";
    version = "4b837f489c8fcff97c159917308a501632f92a25";
    src = fetchgit {
      url = "https://github.com/lobehub/lobe-icons.git";
      rev = "4b837f489c8fcff97c159917308a501632f92a25";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sNc54FnpT2vytNPHWzFxwlhP/kTTpytDS+qVm0t+V3A=";
    };
    date = "2026-05-28";
  };
  noname = {
    pname = "noname";
    version = "v1.11.4";
    src = fetchFromGitHub {
      owner = "libnoname";
      repo = "noname";
      rev = "v1.11.4";
      fetchSubmodules = false;
      sha256 = "sha256-03ot2ENF8UqiUNbzQTf00rvNr11/wV2tjQobKlrwwE0=";
    };
  };
  rime_wanxiang_flypy = {
    pname = "rime_wanxiang_flypy";
    version = "v15.12.5";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v15.12.5/rime-wanxiang-flypy-fuzhu.zip";
      sha256 = "sha256-ZdQJeDE43S8abm5GInIMz9znnUDlkPjvx0GlzEyGmKA=";
    };
  };
  rime_wanxiang_zrm = {
    pname = "rime_wanxiang_zrm";
    version = "v15.12.5";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v15.12.5/rime-wanxiang-zrm-fuzhu.zip";
      sha256 = "sha256-b+ASmDaIomcdtW25Rp21TB7zILp/R7m+TIpv0dB3EOk=";
    };
  };
}
