# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  RIME-LMDG = {
    pname = "RIME-LMDG";
    version = "dict-nightly";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram";
      sha256 = "sha256-XNANGNCLnhPOnS06LkY3C03oslqlHrdOs8jRsEQa5TI=";
    };
  };
  bbdown-linux-arm64 = {
    pname = "bbdown-linux-arm64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_linux-arm64.zip";
      sha256 = "sha256-9Y4KGN8aWJN1QooK8n6mH1zpb/r2fRFfM11fm+6aNNw=";
    };
  };
  bbdown-linux-x64 = {
    pname = "bbdown-linux-x64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_linux-x64.zip";
      sha256 = "sha256-7CM7fY1AscxER9rAW+ND9Tp1fcYFdDqICKuqjpfl0Q4=";
    };
  };
  bbdown-osx-arm64 = {
    pname = "bbdown-osx-arm64";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/nilaoda/BBDown/releases/download/1.6.3/BBDown_1.6.3_20240814_osx-arm64.zip";
      sha256 = "sha256-TfhAFNgYvW3/KzZbhHZFNA6JVcRFD+llaI9Br4mji6o=";
    };
  };
  noname = {
    pname = "noname";
    version = "v1.11.3";
    src = fetchFromGitHub {
      owner = "libnoname";
      repo = "noname";
      rev = "v1.11.3";
      fetchSubmodules = false;
      sha256 = "sha256-NXm9nFdTAvcKo9eiNDG1tgFwCfB7waFwEZebLv8ah3c=";
    };
  };
  rime_wanxiang_flypy = {
    pname = "rime_wanxiang_flypy";
    version = "v15.7.1";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v15.7.1/rime-wanxiang-flypy-fuzhu.zip";
      sha256 = "sha256-39M9HO+rUFuUtqZLL8ZYXKYbORLAZGIlGIUP4IOQwdw=";
    };
  };
  rime_wanxiang_zrm = {
    pname = "rime_wanxiang_zrm";
    version = "v15.7.1";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v15.7.1/rime-wanxiang-zrm-fuzhu.zip";
      sha256 = "sha256-X9Ef+Uxr+9COljsXDAa6PtUFui7NWfsDF9+boyFZRrg=";
    };
  };
}
