# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  RIME-LMDG = {
    pname = "RIME-LMDG";
    version = "dict-nightly";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram";
      sha256 = "sha256-XNANGNCLnhPOnS06LkY3C03oslqlHrdOs8jRsEQa5TI=";
    };
  };
  rime_wanxiang_flypy = {
    pname = "rime_wanxiang_flypy";
    version = "v15.7.1";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v15.7.1/rime-wanxiang-flypy-fuzhu.zip";
      sha256 = "sha256-39M9HO+rUFuUtqZLL8ZYXKYbORLAZGIlGIUP4IOQwdw=";
    };
  };
  rime_wanxiang_zrm = {
    pname = "rime_wanxiang_zrm";
    version = "v15.7.1";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v15.7.1/rime-wanxiang-zrm-fuzhu.zip";
      sha256 = "sha256-X9Ef+Uxr+9COljsXDAa6PtUFui7NWfsDF9+boyFZRrg=";
    };
  };
}
