{
  flake.nixosModules.desktop = { pkgs, ... }: {
    environment.systemPackages = with pkgs; [
      # keep-sorted start
      efibootmgr
      f2fs-tools
      gnome-firmware
      libnotify
      libva-utils
      lm_sensors
      ltrace
      mesa-demos
      nvme-cli
      openvpn
      pciutils
      sbctl
      smartmontools
      strace
      usbutils
      v4l-utils
      vulkan-tools
      wayland-utils
      wf-recorder
      wl-clipboard
      # keep-sorted end

      mat2
      metadata-cleaner

      loupe # SUPER FAST 有催人跑的感觉
      mpv
      sioyek

      zenity

      d-spy # dbus viewer
    ];
    programs.gnome-disks.enable = true;
    programs.gpu-screen-recorder.enable = true;
    environment.sessionVariables = {
      NIXOS_OZONE_WL = 1;
    };
    # hardware.fancontrol = {
    #   enable = true;
    #   config = ''
    #     # Configuration file generated by pwmconfig
    #     INTERVAL=10
    #     DEVPATH=hwmon3=devices/virtual/thermal/thermal_zone2 hwmon4=devices/platform/f71882fg.656
    #     DEVNAME=hwmon3=soc_dts1 hwmon4=f71869a
    #     FCTEMPS=hwmon4/device/pwm1=hwmon3/temp1_input
    #     FCFANS=hwmon4/device/pwm1=hwmon4/device/fan1_input
    #     MINTEMP=hwmon4/device/pwm1=35
    #     MAXTEMP=hwmon4/device/pwm1=65
    #     MINSTART=hwmon4/device/pwm1=150
    #     MINSTOP=hwmon4/device/pwm1=0
    #   '';
    # };
  };
  flake.homeModules.desktop = { pkgs, lib, ... }: {
    home.packages =
      with pkgs;
      [
        ripgrep-all
        localPkgs.edit-clipboard
        localsend
        pandoc
        dos2unix
        gron
        httpie
        jless
        jq
        yq-go
      ]
      ++ ((lib.optionals pkgs.stdenv.hostPlatform.isLinux) [
        # keep-sorted start
        bluetui
        dex
        ffmpeg
        imagemagick
        kdePackages.ark
        # Image Viewer
        nixpaks.ticktick
        # Theming
        papirus-icon-theme
        qbittorrent
        qpwgraph
        remmina
        ripdrag
        showmethekey
        signal-desktop
        siyuan
        # keep-sorted end
      ])
      ++ ((lib.optionals pkgs.stdenv.hostPlatform.isDarwin) [
        # keep-sorted start
        betterdisplay
        macism # swift-native im-select alternative
        orbstack
        # keep-sorted end
      ]);

    js0ny.homebrew = {
      taps = [
        # "daipeihust/tap" # im-select
      ];
      formulae = [
        # "daipeihust/tap/im-select"
        "folderify"
      ];
      casks = [
        "ticktick"
        "proton-drive"
      ];
    };

    home.sessionVariables = lib.optionalAttrs (pkgs.stdenv.hostPlatform.isLinux) {
      PROTON_PASS_LINUX_KEYRING = "dbus";
    };

    nixdots.persist.nosnap.home.directories = [ ".config/ticktick" ];
  };
}
