{
  lib,
  config,
  pkgs,
  ...
}:
let
  cfg = config.nixdots.persist;
  path = cfg.path; # /persist
  user = config.nixdots.user.name;
in
lib.mkMerge [
  (lib.mkIf cfg.enable {
    programs.fuse.userAllowOther = true;

    environment.persistence."${path}" = {
      hideMounts = true;
      directories = cfg.system.directories;
      files = cfg.system.files;
    };
    # HashedPassword is required for boot
    users.mutableUsers = lib.mkForce false;

    fileSystems."${path}".neededForBoot = true;

  })
  (lib.mkIf cfg.nosnap.enable {
    systemd.tmpfiles.rules = [
      "d ${cfg.nosnap.path} 0755 root root -"
      "d ${cfg.nosnap.path}/home 0755 root root -"
      "d ${cfg.nosnap.path}/home/${user} 0755 ${user} users -"
    ];
    environment.persistence."${cfg.nosnap.path}" = {
      hideMounts = true;
      directories = cfg.nosnap.system.directories;
      files = cfg.nosnap.system.files;
    };
    fileSystems."${cfg.nosnap.path}".neededForBoot = true;
  })
  (lib.mkIf (cfg.rootOn == "btrfs") {
    environment.systemPackages = [ pkgs.localPkgs.impermanence-clean-old-roots ];

    boot.initrd.supportedFilesystems = [ "btrfs" ];

    boot.initrd.systemd.storePaths = with pkgs; [
      btrfs-progs
      coreutils
      findutils
      util-linux
    ];

    boot.initrd.systemd.services.impermanence-rollback = {
      description = "Rollback Btrfs root subvolume";
      wantedBy = [ "initrd.target" ];
      after = [
        "initrd-root-device.target"
        "systemd-udev-settle.service"
      ];
      wants = [ "systemd-udev-settle.service" ];
      before = [ "sysroot.mount" ];
      unitConfig.DefaultDependencies = "no";
      serviceConfig.Type = "oneshot";
      path = with pkgs; [
        btrfs-progs
        coreutils
        findutils
        util-linux
      ];
      script =
        let
          mkdir = lib.getExe' pkgs.coreutils "mkdir";
          mv = lib.getExe' pkgs.coreutils "mv";
          date = lib.getExe' pkgs.coreutils "date";
          mount = lib.getExe' pkgs.util-linux "mount";
          umount = lib.getExe' pkgs.util-linux "umount";
          btrfs = lib.getExe pkgs.btrfs-progs;
          find = lib.getExe pkgs.findutils;
        in
        /* bash */ ''
          ${mkdir} -p /btrfs_tmp

          # Label generated by disko
          ${mount} /dev/disk/by-partlabel/disk-main-root /btrfs_tmp

          # 如果发现旧的 root 子卷
          if [ -e /btrfs_tmp/root ]; then
              ${mkdir} -p /btrfs_tmp/old_roots
              # 兼容 initrd (Busybox) 的时间戳获取方式
              timestamp=$(${date} +%Y-%m-%d_%H-%M-%S)

              # 将本次重启前的旧系统状态移入历史归档
              ${mv} /btrfs_tmp/root "/btrfs_tmp/old_roots/$timestamp"
          fi

          # 清理那些囤积超过 30 天的旧日“根目录”垃圾
          delete_subvolume_recursively() {
              IFS=$'\n'
              for i in $(${btrfs} subvolume list -o "$1" | cut -f 9- -d ' '); do
                  delete_subvolume_recursively "/btrfs_tmp/$i"
              done
              ${btrfs} subvolume delete "$1"
          }

          # 寻找并销毁 30 天前的归档
          for i in $(${find} /btrfs_tmp/old_roots/ -mindepth 1 -maxdepth 1 -mtime +30); do
              delete_subvolume_recursively "$i"
          done

          # 为本次开机创建一个绝对纯净的全新根卷
          ${btrfs} subvolume create /btrfs_tmp/root

          ${umount} /btrfs_tmp
        '';
    };
  })
]
